version: '3'
services:
  node_js_server:
    env_file: '.env'
    container_name: node_js_server
    build: .
    ports:
      - '${NODE_JS_PORT}:3003'
    volumes:
      - ./news_api/:/var/www/news_api
    restart: always
    links:
      - mongo_db
    depends_on:
      - mongo_db
  mongo_db:
    env_file: '.env'
    container_name: mongo_db
    image: mongo:6-jammy
    restart: always
    ports:
      - "${MONGO_PORT}:27017"
    volumes:
      - mongodbdata:/data/db

volumes:
  mongodbdata:
    driver: local